Trying:
    add_integer = __import__('0-add_integer').add_integer
Expecting nothing
ok
Trying:
    add_integer(0)
Expecting:
    98
ok
Trying:
    add_integer(1, 1)
Expecting:
    2
ok
Trying:
    add_integer(1, 0)
Expecting:
    1
ok
Trying:
    add_integer(-1, 2)
Expecting:
    1
ok
Trying:
    add_integer(1, -3)
Expecting:
    -2
ok
Trying:
    add_integer(5.236, 2.98)
Expecting:
    7
ok
Trying:
    add_integer(-0.9, -2)
Expecting:
    -2
ok
Trying:
    add_integer('baba', jabli)
Expecting:
    Traceback (most recent call last):
    TypeError: a must be an integer
**********************************************************************
File "tests/0-add_integer.txt", line 37, in 0-add_integer.txt
Failed example:
    add_integer('baba', jabli)
Expected:
    Traceback (most recent call last):
    TypeError: a must be an integer
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[8]>", line 1, in <module>
        add_integer('baba', jabli)
    NameError: name 'jabli' is not defined
Trying:
    add_integer(8, "ya3ini")
Expecting:
    Traceback (most recent call last):
    TypeError: b must be an integer
**********************************************************************
File "tests/0-add_integer.txt", line 41, in 0-add_integer.txt
Failed example:
    add_integer(8, "ya3ini")
Expected:
    Traceback (most recent call last):
    TypeError: b must be an integer
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[9]>", line 1, in <module>
        add_integer(8, "ya3ini")
      File "/home/lwssim/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 27, in add_integer
        raise TypeError("{} must be an integer".format(i))
    TypeError: ya3ini must be an integer
Trying:
    add_integer(None)
Expecting:
    Traceback (most recent call last):
    TypeError: a must be an integer
**********************************************************************
File "tests/0-add_integer.txt", line 45, in 0-add_integer.txt
Failed example:
    add_integer(None)
Expected:
    Traceback (most recent call last):
    TypeError: a must be an integer
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[10]>", line 1, in <module>
        add_integer(None)
      File "/home/lwssim/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 27, in add_integer
        raise TypeError("{} must be an integer".format(i))
    TypeError: None must be an integer
Trying:
    add_integer(float(inf))
Expecting:
    Traceback (most recent call last)
**********************************************************************
File "tests/0-add_integer.txt", line 55, in 0-add_integer.txt
Failed example:
    add_integer(float(inf))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[11]>", line 1, in <module>
        add_integer(float(inf))
    NameError: name 'inf' is not defined
**********************************************************************
1 items had failures:
   4 of  12 in 0-add_integer.txt
12 tests in 1 items.
8 passed and 4 failed.
***Test Failed*** 4 failures.
